theme: "jekyll-theme-hacker"

title: "The r/ASRock Wiki"
tagline: "An ASRock releated Wiki made by the ASRock Community for the ASRock Community"
description: "This is the r/ASRock Wiki - Here you will find a bunch of Guides and Tools. Including an FAQ, a Beta BIOS database and more!"
url: "https://botflakes.github.io"
twitter:
  card: "summary_large_image"
  username: "redditASRock"

plugins:
  - jekyll-seo-tag
  - jemoji
  - jekyll-sitemap
safe: false