url: "https://botflakes.github.io/ASRockWiki/" 
theme: jekyll-theme-hacker
title: r/ASRock > Wiki
description: The r/ASRock Wiki
github:
  is_project_page: false
plugins:
  - jemoji
  - jekyll-sitemap
safe: false
