url: "https://botflakes.github.io" 
theme: jekyll-theme-hacker
title: The r/ASRock Wiki
tagline: A ASRock releated Wiki made by u/CornFlakes1991
description: This is the r/ASRock Wiki - Here you will find a bunch of Guides and Tools. Including an FAQ, a Beta BIOS database and more!
author:
  twitter: CornFlakesPC
twitter:
  username: redditASRock
  card: summary
  logo: assets/images/logo.png
social:
  name: r/ASRock
  links:
    - https://twitter.com/redditASRock
    - https://discord.gg/rFrMpxV
image: 
  path: assets/images/social_card.png
  width: 1280
  height: 640
github:
  is_project_page: false
plugins:
  - jekyll-seo-tag
  - jemoji
  - jekyll-sitemap
safe: false
